#!/bin/bash

sudo docker build --build-arg ACCS_BRANCH=master --build-arg AS_BRANCH=develop --build-arg COMMON_BRANCH=master \
    --no-cache -t fogbow/accounting-service:latest -t fogbow/accounting-service:master .

